update

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -28,12 +28,22 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
+      - name: Checkout repository
         uses: actions/checkout@v4
 
-      # Copy PDF to the build directory
-      - name: Copy PDF to build directory
-        run: cp ./docs/Khalil_Unterlagen.pdf ./public/
+      # Debugging: List files to ensure the file exists
+      - name: List files for debugging
+        run: ls -R
+
+      # Copy PDF from docs to public directory
+      - name: Copy PDF to public directory
+        run: |
+          if [ -f "./docs/Khalil_Unterlagen.pdf" ]; then
+            cp ./docs/Khalil_Unterlagen.pdf ./public/
+          else
+            echo "PDF file not found in docs/"
+            exit 1
+          fi
 
       # Detect package manager (npm/yarn)
       - name: Detect package manager
@@ -59,26 +69,18 @@ jobs:
         with:
           node-version: "20"
           cache: ${{ steps.detect-package-manager.outputs.manager }}
-      - name: Setup Pages
-        uses: actions/configure-pages@v5
-        with:
-          static_site_generator: next
-      - name: Restore cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            .next/cache
-          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
-          restore-keys: |
-            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+
       - name: Install dependencies
         run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+
       - name: Build with Next.js
         run: ${{ steps.detect-package-manager.outputs.runner }} next build
+
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
           path: ./dist
+
 
   # Deployment job
   deploy:
